apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-batch
  description: "Microsserviço responsável pelo processamento batch em csv"
  owner: mwacha
  tags:
    - springboot
    - swagger
    - java
spec:
  type: service
  lifecycle: production
  owner: mwacha
  system: backend
  providesApis:
    - "default/hello-api"  # Nome da API fornecida pelo serviço
    - "default/startJob-api"
    - "default/import-products-api"
  consumesApis: []
  links:
    - url: "https://github.com/mwacha/springboot-batch"
      title: "Repo"
    - url: "http://localhost:8080/swagger-ui.html"
      title: "Swagger UI"
    - url: "http://localhost:8080/actuator"
      title: "Actuator"

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-api
  description: "API para saudações do microsserviço Spring Boot Batch"
  owner: mwacha
spec:
  type: openapi
  lifecycle: production
  owner: mwacha
  definition:
    $text: http://localhost:8080/v3/api-docs

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: startJob-api
  description: "API para iniciar um job"
  owner: mwacha
spec:
  type: openapi
  lifecycle: production
  owner: mwacha
  definition:
    $text: http://localhost:8080/api/startJob

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: import-products-api
  description: "API para importar produtos"
  owner: mwacha
spec:
  type: openapi
  lifecycle: production
  owner: mwacha
  definition:
    $text: http://localhost:8080/api/import-products
