version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  pocs-db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pocs
      POSTGRES_USER: pocs
      POSTGRES_PASSWORD: poc123
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U pocs" ]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - pocs-network

networks:
  pocs-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data: