#: Application configuration
spring:
  batch:
      initialize-schema: always
  flyway:
    baselineOnMigrate: true
  application:
    name: springbtach
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pocs
    username: pocs
    password: poc123
  servlet:
    multipart.max-file-size: 10MB
    max-request-size: 10MB
    resolve-lazily: true

file:
  input: product.csv